# Generated by Django 5.2.12 on 2026-03-24 18:24

import django.db.models.deletion
import django_ulidfield.fields
import ulid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', django_ulidfield.fields.ULIDField(default=ulid.ULID, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(default='pending', max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('dateCreated', models.DateTimeField(auto_created=True)),
                ('id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('image', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('accountId', models.OneToOneField(db_column='accountId', on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Candidate',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('accountId', models.OneToOneField(db_column='accountId', on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employer',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('companyName', models.CharField(max_length=255)),
                ('tradingName', models.CharField(max_length=100)),
                ('link', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('scale', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('employerId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app.employer')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('name', models.CharField(max_length=255)),
                ('sourceLink', models.TextField(db_index=True, null=True)),
                ('description', models.TextField(null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateLimited', models.DateTimeField()),
                ('companyId', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app.company')),
            ],
            options={
                'db_table': 'Job',
            },
        ),
        migrations.CreateModel(
            name='JobDesc',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('index', models.IntegerField(default=0)),
                ('jobId', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='app.job')),
            ],
            options={
                'db_table': 'JobDesc',
            },
        ),
        migrations.CreateModel(
            name='JobReq',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('formOfJob', models.CharField(default='Không yêu cầu', max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('salary', models.CharField(default='Thỏa thuận', max_length=100, null=True)),
                ('career', models.CharField(default='Không yêu cầu', max_length=255, null=True)),
                ('education', models.CharField(default='Không yêu cầu', max_length=255, null=True)),
                ('experience', models.CharField(default='Không yêu cầu', max_length=10, null=True)),
                ('jobId', models.OneToOneField(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='req', to='app.job')),
            ],
            options={
                'db_table': 'JobReq',
            },
        ),
        migrations.CreateModel(
            name='JobSaved',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('accountId', models.ForeignKey(db_column='accountId', on_delete=django.db.models.deletion.CASCADE, related_name='job_saved', to=settings.AUTH_USER_MODEL)),
                ('jobId', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app.job')),
            ],
            options={
                'db_table': 'JobSaved',
            },
        ),
    ]
