# Generated by Django 5.2.12 on 2026-04-01 15:11

import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_status_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreated'),
        ),
        migrations.RenameField(
            model_name='account',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='accountId',
            new_name='account_id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dateCreated',
            field=models.DateTimeField(auto_created=True, db_column='dateCreated'),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='company',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreated'),
        ),
        migrations.RenameField(
            model_name='company',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='accountId',
            new_name='account_id',
        ),
        migrations.AlterField(
            model_name='employer',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreated'),
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='job',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreated'),
        ),
        migrations.RenameField(
            model_name='job',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='job',
            name='dateLimited',
            field=models.DateTimeField(db_column='dateLimited'),
        ),
        migrations.RenameField(
            model_name='job',
            old_name='dateLimited',
            new_name='date_limited',
        ),
        migrations.AlterField(
            model_name='job',
            name='sourceLink',
            field=models.TextField(db_column='sourceLink', db_index=True, null=True),
        ),
        migrations.RenameField(
            model_name='job',
            old_name='sourceLink',
            new_name='source_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employerId',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tradingName',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(db_column='phoneNumber', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_domain',
            field=models.CharField(db_column='emailDomain', default='@name.com', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='is_claimed',
            field=models.BooleanField(db_column='isClaimed', default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(db_column='isVerified', default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='trading_name',
            field=models.CharField(db_column='tradingName', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='company',
            name='scale',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='jobdesc',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='jobreq',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
        migrations.AlterField(
            model_name='jobsaved',
            name='id',
            field=django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid]),
        ),
    ]
