# Generated by Django 5.2.12 on 2026-04-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_datecreated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='companyId',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='jobdesc',
            old_name='jobId',
            new_name='job_id',
        ),
        migrations.AlterField(
            model_name='jobreq',
            name='formOfJob',
            field=models.CharField(db_column='formOfJob', default='Không yêu cầu', max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='jobreq',
            old_name='formOfJob',
            new_name='form_of_job',
        ),
        migrations.RenameField(
            model_name='jobreq',
            old_name='jobId',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='jobsaved',
            old_name='accountId',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='jobsaved',
            old_name='jobId',
            new_name='job_id',
        ),
    ]
