# Generated by Django 5.2.12 on 2026-04-01 15:40

import django.db.models.deletion
import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_companyid_job_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('role', models.CharField(default='pending', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dateCreated')),
                ('company_id', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='app.company')),
                ('employer_id', models.ForeignKey(db_column='employerId', on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='app.employer')),
            ],
            options={
                'db_table': 'CompanyUser',
                'unique_together': {('employer_id', 'company_id')},
            },
        ),
    ]
