# Generated by Django 5.2.12 on 2026-04-01 20:30

import django.db.models.deletion
import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_companyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Industry',
            },
        ),
        migrations.CreateModel(
            name='IndustryTranslations',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('language_code', models.CharField(db_column='languageCode', max_length=5, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('industry_id', models.ForeignKey(db_column='industryId', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.industry')),
            ],
            options={
                'db_table': 'IndustryTranslations',
            },
        ),
    ]
