# Generated by Django 5.2.12 on 2026-04-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_industry_industrytranslations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreq',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobreq',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobreq',
            name='max_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobreq',
            name='max_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobreq',
            name='min_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobreq',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
    ]
