# Generated by Django 5.2.12 on 2026-04-13 13:49

import django.db.models.deletion
import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_jobreq_experience_remove_jobreq_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'JobLevel',
            },
        ),
        migrations.CreateModel(
            name='JobLevelTranslations',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('language_code', models.CharField(db_column='languageCode', max_length=5, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('job_level_id', models.ForeignKey(db_column='jobLevelId', on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='app.joblevel')),
            ],
            options={
                'db_table': 'JobLevelTranslations',
            },
        ),
    ]
