# Generated by Django 5.2.12 on 2026-04-13 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_joblevel_jobleveltranslations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobleveltranslations',
            name='job_level_id',
            field=models.ForeignKey(db_column='jobLevelId', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.joblevel'),
        ),
    ]
