# Generated by Django 5.2.12 on 2026-04-13 15:54

import django.db.models.deletion
import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_jobleveltranslations_job_level_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('slug', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'Education',
            },
        ),
        migrations.CreateModel(
            name='FormOfWork',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'FormOfWork',
            },
        ),
        migrations.AlterField(
            model_name='joblevel',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='EducationTranslations',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('language_code', models.CharField(db_column='languageCode', max_length=5, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('education_id', models.ForeignKey(db_column='educationId', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.education')),
            ],
            options={
                'db_table': 'EducationTranslations',
            },
        ),
        migrations.CreateModel(
            name='FormOfWorkTranslations',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('language_code', models.CharField(db_column='LanguageCode', max_length=5, null=True)),
                ('name', models.CharField(db_column='Name', max_length=255, null=True)),
                ('form_of_work_id', models.ForeignKey(db_column='FormOfWorkId', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.formofwork')),
            ],
            options={
                'db_table': 'FormOfWorkTranslations',
            },
        ),
    ]
