# Generated by Django 5.2.12 on 2026-04-20 17:19

import django.db.models.deletion
import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_education_formofwork_alter_joblevel_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('type', models.CharField(choices=[('country', 'Country'), ('city', 'City'), ('district', 'District')], db_index=True, max_length=20)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('parent_id', models.ForeignKey(db_column='parentId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.locations')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='LocationTranslations',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('language_code', models.CharField(db_column='languageCode', max_length=5, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('location_id', models.ForeignKey(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='app.locations')),
            ],
            options={
                'db_table': 'LocationTranslations',
            },
        ),
    ]
