# Generated by Django 5.2.12 on 2026-04-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_locations_locationtranslations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locations',
            table='Locations',
        ),
    ]
