# Generated by Django 5.2.12 on 2026-04-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_locations_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtranslations',
            name='location_id',
            field=models.ForeignKey(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.locations'),
        ),
    ]
