# Generated by Django 5.2.12 on 2026-05-11 14:59

import django.db.models.deletion
import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_locationtranslations_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='link',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='scale',
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_name',
            field=models.CharField(db_column='tradingName', default='', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('date_create', models.DateTimeField(auto_now_add=True, db_column='dateCreate', db_index=True)),
                ('company', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='company_industries', to='app.company')),
                ('industry', models.ForeignKey(db_column='industryId', on_delete=django.db.models.deletion.CASCADE, related_name='industry_companies', to='app.industry')),
            ],
            options={
                'db_table': 'CompanyIndustry',
                'unique_together': {('company', 'industry')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(related_name='companies', through='app.CompanyIndustry', to='app.industry'),
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', django_ulidfield.fields.ULIDField(db_index=True, default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('detail_address', models.CharField(blank=True, db_column='detailAddress', max_length=255, null=True)),
                ('date_create', models.DateField(blank=True, db_column='dateCreate', null=True)),
                ('company', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='company_locations', to='app.company')),
                ('location', models.ForeignKey(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, related_name='location_companies', to='app.locations')),
            ],
            options={
                'db_table': 'CompanyLocation',
                'unique_together': {('company', 'location')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(related_name='companies', through='app.CompanyLocation', to='app.locations'),
        ),
    ]
